[+] Added 18 lesson task (websocket based chat)
svowl/go-core pull request #26
Opened 2020-12-13 14:30 UTC by svowl

Извиняюсь за многословность - использовал тотальное логгирование всех действий в серверном приложении, убирать не стал...

2020-12-13 14:35 UTC, svowl commented
Стоп. Забыл про lock :(
Сейчас добавлю

2020-12-17 04:12 UTC, DmitriyVTitov requested changes
Каналы сообщений клиентов не удалятся из массива.

2020-12-17 04:12 UTC, DmitriyVTitov commented on 18-lesson/cmd/chat_server/chat_api.go
> +	s.nextConnID = 0
и так было бы 0

2020-12-17 04:12 UTC, DmitriyVTitov commented on 18-lesson/cmd/chat_server/chat_api.go
> +		}
authorized = true - выглядит избыточно.
если неверный пароль - завершили обработчик и всё, если продолжаем - то ОК

2020-12-17 04:12 UTC, DmitriyVTitov commented on 18-lesson/cmd/chat_server/chat_api.go
> +}
эта функция нигде не вызывается

2020-12-18 09:39 UTC, closed without merging